### ISSUE TITLE
dataframe-core-1.1.0.0 doesn't build with GHC 9.6.7

### ISSUE THREAD

**Issue by mistransky** [mchav/dataframe#206]
Fails to build due  to a typing error while compiling src/DataFrame/Internal/RadixRank.hs

**To Reproduce**
using GHC 9.6.7 installed using GHCup

1. cabal init
2. add dependency: dataframe-2.2.0.0  which now pulls dataframe-core-1.1.0.0
3. cabal build (or repl)

**Output**
```
Building library for dataframe-core-1.1.0.0...
...
...
src/DataFrame/Internal/RadixRank.hs:79:38: error: [GHC-39999]
    • Could not deduce ‘VUM.Unbox a’
        arising from a use of ‘VUM.unsafeRead’
      from the context: PrimMonad m
        bound by the type signature for:
                   rankByHash :: forall (m :: * -> *).
                                 PrimMonad m =>
                                 (Int -> m Int) -> Int -> m (VU.Vector Int)
        at src/DataFrame/Internal/RadixRank.hs:(38,1)-(39,63)
      or from: (VUM.PrimState f ~ VUM.PrimState m, PrimMonad f)
        bound by the inferred type of
                   place :: (VUM.PrimState f ~ VUM.PrimState m, PrimMonad f) =>
                            Int -> f ()
        at src/DataFrame/Internal/RadixRank.hs:(75,25)-(85,45)
      Possible fix:
        add (VUM.Unbox a) to the context of
          the inferred type of
            place :: (VUM.PrimState f ~ VUM.PrimState m, PrimMonad f) =>
                     Int -> f ()
          or the inferred type of
               pass :: Int
                       -> VUM.MVector (VUM.PrimState m) Int
                       -> VUM.MVector (VUM.PrimState m) a
                       -> VUM.MVector (VUM.PrimState m) Int
                       -> VUM.MVector (VUM.PrimState m) a
                       -> m ()
    • In a stmt of a 'do' block: o <- VUM.unsafeRead srcO i
      In the expression:
        do k <- VUM.unsafeRead srcK i
           o <- VUM.unsafeRead srcO i
           let !b = (k `unsafeShiftR` shiftBits) .&. 0xff
           pos <- VUM.unsafeRead counts b
           ....
      In an equation for ‘place’:
          place !i
            | i >= ng = pure ()
            | otherwise
            = do k <- VUM.unsafeRead srcK i
                 o <- VUM.unsafeRead srcO i
                 let !b = ...
                 ....
   |
79 |                                 o <- VUM.unsafeRead srcO i
   |                                      ^^^^^^^^^^^^^^
```

**Machine:**
 - OS: Fedora 44
 - CPU: Intel x86_64
 - GHC 9.6.7
 - GHCup 0.2.6.1
 - cabal 3.14.2.0

**Note:**
It builds fine on my machine with GHC 9.10.3, with the rest of the tools above the same.

**Comment by mchav** [comment]
Thanks for catching this. The CI flagged the same issue - should have addressed it then. Releasing a new version of core o hackage.
